### ISSUE TITLE
QueryDemo won't build

### ISSUE THREAD

**Issue by icanzilb** [groue/GRDBQuery#1]
I downloaded the package and opened QueryDemo but I'm getting a compile error (Xcode 13.2)

<img width="265" alt="image" src="https://user-images.githubusercontent.com/633862/143495546-830d9cd8-b32b-40e1-aded-575bdffc5b7c.png">

**Comment by groue** [comment]
Hello @icanzilb, that's a pity! Maybe I made a stupid mistake, let me check.

**Comment by groue** [comment]
I got the same problem from a fresh clone, with erased DerivedData folder.

However, after opening the demo project, seeing this error, then quitting Xcode and reopening the project, the build ran fine.

Is it the same for you?

I wonder if there is a way to workaround this Xcode glitch...

**Comment by groue** [comment]
It's the same with Xcode 13.2 beta 2. Talk about a bad first contact 😞

I'll see what I can learn on Google about local packages caveats. Thanks for reporting!

**Comment by icanzilb** [comment]
Huh, you are right ... closing and opening the project again builds and runs with no issues 😬 This is definitely an issue with Xcode, good that you already have a sample project to attach if you create a feedback 😁

**Comment by groue** [comment]
> This is definitely an issue with Xcode, good that you already have a sample project to attach if you create a feedback 😁

Good idea 👍 Reported as FB9781232.

**Comment by groue** [comment]
I'll close and pin this issue. This is just an Xcode bug, nothing we can really fix.
