### ISSUE TITLE
How to implement the equals method on Queryable protocol correctly?

### ISSUE THREAD

**Issue by Jasperav** [groue/GRDBQuery#13]
The Queryable protocol conforms to the Equatable protocol, how should I implement it for a query which do not have parameters in the query (no where clause)? E.g.:

https://github.com/Jasperav/GRDB-ORM/blob/dba6a5399e959eeb4a22b0d7652a36ca97812a0b/GRDBPerformance/GRDBPerformance/Generated/DynamicQueries.swift#L119

**Comment by groue** [comment]
Hello @Jasperav,

Generally speaking, you turn a non-equatable type into an equatable one with one of these techniques:

1. Provide a sensible implementation for `==`.
2. Make all properties equatable.
3. Find an alternative to non-equatable properties.

Option 1 and 2 are not available in your case, so you have to use option 3.

For example, replace the `scheduler` property with a boolean, or your own enum, which tells which scheduler to use. You don't have much choice beyond `.immediate` or `.async(onQueue: .main)`, anyway. So a `immediate` boolean should do the trick.
