### ISSUE TITLE
No animation on change

### ISSUE THREAD

**Issue by AzSiAz** [groue/GRDBQuery#2]
Hello thanks for this tiny lib around combine support in GRDB (and clever I might add)

I am currently trying to migrate a personal app from CoreData to GRDB, and I am finally enjoying querying data in my app so thanks for this 😄 

But I am stumbling across a problem I don't quite know how to solve...

How can we animate change to `@Query` property with some kind of `withAnimation {}` to be automatically reflected inside the UI ?
I naively tried to surround `model.save(db)` with `withAnimation {}` but as you might have guessed it doesn't work since updated value are coming from `ValueObservation`, I also tried around `ValueObservation` but it's the same

Happy to move this to a discussion if that's not the correct place and just a mistake on my side

**Comment by groue** [comment]
Hello @AzSiAz, thanks! I'm quite away from any computer, and I can't answer until I'm back. Maybe someone else can?

**Comment by groue** [comment]
Meanwhile, you can check how the GRDB demo app animates the changes in a view fee by `@Query`: https://github.com/groue/GRDB.swift/blob/042e220f498af4a545de629d0e5051e8bb1a8139/Documentation/DemoApps/GRDBCombineDemo/GRDBCombineDemo/Views/PlayerList.swift#L25

**Comment by AzSiAz** [comment]
Hello again, sorry for the delay

> Hello @AzSiAz, thanks! I'm quite away from any computer, and I can't answer until I'm back. Maybe someone else can?
No problem, It's not anything urgent and I can completely do without until then

No problem, enjoy your holiday/time off 😄 


> Meanwhile, you can check how the GRDB demo app animates the changes in a view fee by `@Query`: https://github.com/groue/GRDB.swift/blob/042e220f498af4a545de629d0e5051e8bb1a8139/Documentation/DemoApps/GRDBCombineDemo/GRDBCombineDemo/Views/PlayerList.swift#L25

Thanks for the link I didn't saw this way to do it by skimming through the example, doesn't seem to work in my case unfortunately
Seem to work inside the simulator for the demo though so it's probably on my code

In my use case I am using a list with multiple section, and animation between sections is not working, I still have a lot of code to refactor to use GRDB so I will come back to this later probably 

In case someone need to see the [code](https://github.com/AzSiAz/Dokusho/blob/eb696ef95adc1bd25f7d444d985ba5e2643c7b54/Dokusho/Views/ExploreTabView/ExploreTabView.swift)

**Comment by groue** [comment]
> In case someone need to see the [code](https://github.com/AzSiAz/Dokusho/blob/main/Dokusho/Views/ExploreTabView/ExploreTabView.swift)

Actually, it would be more interesting to see the code of your original CoreData app, the part that is related to animations. But even this is unlikely to give good results, because we'll be overwhelmed by details that are unrelated to the issue itself.

I recommend that you isolate a **pattern** that is difficult to translate from CoreData to GRDB.

**Comment by AzSiAz** [comment]
> Actually, it would be more interesting to see the code of your original CoreData app, the part that is related to animations. But even this is unlikely to give good results, because we'll be overwhelmed by details that are unrelated to the issue itself.

Previous [code](https://github.com/AzSiAz/Dokusho/blob/a53a944e245706b02850d09c6120afe0e84cbeeb/Dokusho/Views/ExploreTabView/ExploreTabView.swift) is not that complex but I see your point

> I recommend that you isolate a **pattern** that is difficult to translate from CoreData to GRDB.

The difference might be related to the fact `NSManagedObject` are also `ObservableObject` and I used `withAnimation` on toggle function so it might do entity -> section move animation -> entity list update with `FetchRequest` but no ui change so no new animation.
I am not doing this in GRDB version, I am fetching and updating bypassing entity from `Query` and just using entity id and letting GRDBQuery update to let SwiftUI re-render view

I will try to create a minimal reproduction exemple for next week if I can figure out a way to animate things 

By the way I finished updating my code to use GRDB instead of CoreData and aside from this small animation problem on this view (and only for this one from what I can see), I had no problem porting code to use GRDB with one of the best documentation I have ever seen 💯

**Comment by groue** [comment]
> The difference might be related to the fact `NSManagedObject` are also `ObservableObject` and I used `withAnimation` on toggle function so it might do entity -> section move animation -> entity list update with `FetchRequest` but no ui change so no new animation. I am not doing this in GRDB version, I am fetching and updating bypassing entity from `Query` and just using entity id and letting GRDBQuery update to let SwiftUI re-render view

Ah, yes. Since GRDB records do not auto-update, they can't conform to `ObservableObject`.

> I will try to create a minimal reproduction exemple for next week if I can't figure out a way to animate things

Maybe I can help you narrowing the topic of this issue.

It looks like Core Data lets you specify the desired animation "at mutation time". This lets you pick the animation that should run in response to the user action. If I understand correctly, you can provide two buttons, "Do something" and "Do something animated", which perform the same database change, but result in different ways to update the view.

In contrast, GRDB lets you specify one animation that applies for *all* changes, since the animation is a property of the view.

Does it more or less sum up the issue?

> By the way I finished updating my code to use GRDB instead of CoreData and aside from this small animation problem on this view (and only for this one from what I can see), I had no problem porting code to use GRDB with one of the best documentation I have ever seen 💯

Thank you _very much_ :-) This library aims at helping developers write their apps, so I'm very interested in your feedback 👍

**Comment by groue** [comment]
Why is this issue still open? Please tell if it should be reopened, thanks.
