### ISSUE TITLE
More SwiftUI-Like syntax for the requests

### ISSUE THREAD

**Issue by chriseidhof** [groue/GRDBQuery#20]
I was wondering today whether you could move the syntax a bit closer to what's common in SwiftUI (e.g. with button styles). In the README/demo you have the following code:

```swift
    @Query(PlayerRequest())
    private var player: Player?
```

I thought it would be nice to write it like this:

```swift
    @Query(.player)
    private var player: Player?
```

To make this work, you need to add the following extension:

```swift
extension Queryable where Self == PlayerRequest {
    static var player: Self { PlayerRequest() }
}
```

(Of course, you can do this for the other requests as well).

**Comment by chriseidhof** [comment]
I agree that it adds a bunch of boilerplate (three lines for each view). The usage is nicer (I think) but this also adds a barrier. I think you can also write it as a hint in the docs instead of doing it everywhere. 

And yes, you can already use this today, I changed it in the QueryDemo project and it just works without any extra changes.

**Comment by groue** [comment]
So it looks things are just ok. And I added the SE-0299 tip.
