### ISSUE TITLE
It took me a while...

### ISSUE THREAD

**Issue by crenelle** [groue/GRDBQuery#27]
But I eventually figured out I had to add GRDBQuery as a package dependency to get the demos and test to build :)

**Comment by groue** [comment]
Hello @crenelle,

Do you mean that the demo apps won't build from a fresh clone? That would be unexpected indeed! Maybe you've been hit by #1.

**Comment by crenelle** [comment]
I'm using Xcode 14.0b4. After reading about #1, I reset my local copy back to the state of the repo on github, entered Xcode, opened QueryDemo, changed the Team to me. Then closed Xcode. Started Xcode 14.0b4 again, opened QueryDemo, built. Build succeeded, app started on the iPhone.

Looks like #1 to me.

**Comment by groue** [comment]
All right. I'm not aware of anything that could be done, at the repository level, in order to work around this Xcode bug: I'm closing the issue. If you have an idea, please chime in!
