### ISSUE TITLE
[Bug?] SwiftUI warning in new betas

### ISSUE THREAD

**Issue by fbertuzzi** [groue/GRDBQuery#28]
Hey,

the new Xcode and iOS 16 beta now show a warning which reads as following:

`Publishing changes from within view updates is not allowed, this will cause undefined behavior.`

The highlighted line in code is this one:

https://github.com/groue/GRDBQuery/blob/22df8987f1d0c670970fd730b58b445ae01ce312/Sources/GRDBQuery/Query.swift#L406

I'm not sure if this is just a bug in the new beta, because I haven't had that warning before, or if they changed something in SwiftUI.

I've seen a similar issue when googling the warning on mongodb's realm GitHub:
https://github.com/realm/realm-swift/issues/7908

and some posting on the apple developer forum so it is definitely not a problem which only affects GRDBQuery.

**Comment by groue** [comment]
Hello @fbertuzzi, thank you very much for the report 🙂 

I'm currently in vacations, by I'll look at the issue when I'm back in a few days.

**Comment by groue** [comment]
It looks like SwiftUI no longer wants to support reentrant updates (asking the engine to update a view while it is already updating a view). According to the warning message, this isn't a regression, but rather the sign that they want to strengthen the SwiftUI engine, and reentrant updates are contrary to this goal.

I do not think this will be too difficult to fix on the GRDBQuery side. It's a matter of replacing a a `@Published` property with direct `objectWillChange.send()` (but NOT from the `Tracker.update()` method, taking care of user-provided publishers that immediately publish their initial value right on subscription).

Meanwhile, this is "just" a warning, so I do not expect your app to exhibit bugs.

**Comment by fbertuzzi** [comment]
Hey @groue,

I didn't say its a problem to my app (except for throwing that warning it works normal)! I just noticed this warning so it seems that they've updates something and just wanted to let you know.

Hope you enjoy your few days of vacation!

**Comment by groue** [comment]
Thank you very much for opening this issue! I do enjoy my vacations ;-)

**Comment by groue** [comment]
The fix will ship in the next version.

**Comment by groue** [comment]
TODO: fix the same issue that happens for `EnvironmentStateObject` [there](https://github.com/groue/GRDBQuery/blob/cd2e4ce3816d4ef4536a51a5ed768a956f5cf5d3/Sources/GRDBQuery/EnvironmentStateObject.swift#L315).

**Comment by groue** [comment]
The fix has shipped in version 0.5.0
