### ISSUE TITLE
Using associations in SwiftUI View

### ISSUE THREAD

**Issue by evamedia** [groue/GRDBQuery#3]
I have a has many relationship setup, but not understanding how to access the data within a SwiftUI View.

```
extension Race: TableRecord {
    static var sessions = hasMany(Session.self, using: ForeignKey(["race_id"]))
    var sessions: QueryInterfaceRequest<Session> {
        return request(for: Race.sessions)
    }
}
```

In my View I have

```@Query(RaceRequest(ordering: .byStart)) private var races: [Race]```

Then within the ForEach of races, I want to do a ForEach of sessions but am totally lost

**Comment by groue** [comment]
Hello @evamedia,

It looks like you want to nest two `ForEach`. Did you try to fetch the data that is able to feed both loops?

```swift
struct RaceInfo {
    var race: Race
    var sessions: [Session]
}
```

```swift
@Query(RaceInfoRequest(ordering: .byStart)) private var raceInfos: [RaceInfo]

var body: some View {
    ForEach(raceInfos) { raceInfo in
        RaceView(raceInfo.race)
        ForEach(raceInfos.sessions) { session in
            SessionView(sessions)
        }
    }
}
```

Such a `RaceInfo` struct can be fed with the [`including(all:)`](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#includingall) method.

**Comment by evamedia** [comment]
Hey @groue,

thank you for the response, I seem to failing at understanding where the [including(all:) ](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#includingall) should be.


Inside RaceInfoRequest should it be directly in the default value

```static var defaultValue: [RaceInfo] { [] }```

**Comment by groue** [comment]
`including(all:)` should be in the definition of the query interface request, exactly as documented in the GRDB documentation.

And you observe this request from your Queryable type, as documented in the GRDBQuery documentation.

You should be able to adapt this sample code to your needs:

```swift
import Combine
import GRDB
import GRDBQuery

struct RaceInfo: Decodable, FetchableRecord {
    var race: Race
    var sessions: [Session]
}

struct RaceInfoRequest: Queryable {
    static var defaultValue: [RaceInfo] { [] }
    
    func publisher(in ...) -> AnyPublisher<[RaceInfo], Error> {
        let request = Race
            .including(all: Race.sessions)
            .asRequest(of: RaceInfo.self)
        
        return ValueObservation
            .tracking { db in try request.fetchAll(db) }
            .publisher(in: ...)
            .eraseToAnyPublisher()
    }
}
```
