### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by disbelief** [groue/GRDBQuery#30]
(Sorry for the noob question)

I'm using Cocoapods in my app. Adding `pod 'GRDBQuery'` to the Podfile doesn't work. Should I import this project as a git submodule? What's the recommended way to get GRDBQuery added to an existing project/app?

**Comment by groue** [comment]
Hi @disbelief,

GRDBQuery currently ships as an SPM package only. No one has requested support for CocoaPods yet.

If the SPM option does not work for you, it should be possible to add CocoaPods support to GRDBQuery: just tell (and be ready to wait just a little bit)!

**Comment by borisskert** [comment]
I installed GRDBQuery by adding it as Swift package:

In XCode:
- `File` -> `Add Packages`
- paste the Git repository URL (`https://github.com/groue/GRDBQuery`) into the Search TextBox in the upper right corner
- Click `Add package` Button

(I'm also a noob in Swift)

**Comment by disbelief** [comment]
Thanks @groue and @borisskert I figured out how to do it. Had not used Swift package manager before. No need to use your valuable time supporting Cocoapods just on my behalf.

Would be interested to see an example implementation of MVVM with `@EnvironmentStateObject` though! 😉

**Comment by groue** [comment]
There are two demo apps in the Documentation folder. One is using `@EnvironmentStateObject`.

**Comment by disbelief** [comment]
I somehow missed that. Thank you.

**Comment by groue** [comment]
You're welcome! Happy GRDBQuery :-)

**Comment by jefemagril** [comment]
I was looking for a CocoaPods option also. Any plans to add it?

**Comment by groue** [comment]
Hello @jefemagril, there is currently no plan to add support for CocoaPods. Not only SPM is getting traction, but CocoaPods is [sending bad signals](https://github.com/CocoaPods/CocoaPods/issues/11839), after so many years of near-perfection. Maybe you have good reasons for wishing that GRDBQuery would support CocoaPods?

**Comment by jefemagril** [comment]
Thank you for the reply @groue and thank you for linking so that I can understand the context. I’m still a newbie to this. I have learned that CocoaPods is often the preferable package manager, but I guess that’s recently changing. No, I don’t have good reasons, I can look into other methods.

**Comment by groue** [comment]
OK @jefemagril! I hope the Swift Package Manager, the built-in solution of the Swift ecosystem, will serve you well. It does not come without shortcomings due to its relatively young age. Yet setting up a typical app with GRDB, GRDBQuery, and other packages of your choice is well supported :-) The Xcode documentation has a [page about it](https://developer.apple.com/documentation/xcode/adding-package-dependencies-to-your-app).
