### ISSUE TITLE
@Query support DatabasePool as DatabaseContext?

### ISSUE THREAD

**Issue by jhoughjr** [groue/GRDBQuery#31]
GRDB docs indicate that DatabasePool and DatabaseQueue can be used the same way, but
this does not extend to GRDBQuery.

It seems if Query could work with a pool the same way GRDB does in its api it would work as is
Maybe I'm missing something as the docs say to only ever open one connection to 1 file be it pool or queue, which if so really makes it seem like Query needs to work with pools too.
I understood it as a pool allowed multiple access to the same file from different locations.

**Comment by jhoughjr** [comment]
I may have solved my own issue in a wacky way:
```

struct PlacesRequest: Queryable {
    static var defaultValue: [Place] { [Place]() }
    
    func publisher(in dbQueue: DatabaseQueue) -> AnyPublisher<[Place], Error> {
        ValueObservation
            .tracking { db in
                try Place.fetchAll(db)
                
            }
            // The `.immediate` scheduling feeds the view right on subscription,
            // and avoids an initial rendering with an empty list:
            .publisher(in: DataController.shared.dbPool!, scheduling: .immediate)
            .eraseToAnyPublisher()
    }
}```

feels wrong to ignore what was passed in, but also points to Query supporting a pool as the in: param as I could use a pool at its call site.

**Comment by groue** [comment]
Hello @jhoughjr,

The [Getting Started with @Query](https://swiftpackageindex.com/groue/grdbquery/0.5.1/documentation/grdbquery/gettingstarted) documentation guide contains this paragraphs:

> To use `@Query`, first define a new environment key that grants access to the database.
>
> In the example below, we define a new `dbQueue` environment key whose value is a GRDB DatabaseQueue. Some other apps, like the [GRDB demo apps](https://github.com/groue/GRDB.swift/tree/master/Documentation/DemoApps), can choose another name and another type, such as a “database manager” that encapsulates database accesses.
>
> You are free to choose any type you want, as long as it is possible to create Combine publishers out of it, the publishers of database values that will feed the SwiftUI views.

What this means is that you can put a `DatabasePool` in the environment when a `DatabaseQueue` does not fit your app. You can freely chose the name of your environment key as well.

**Comment by jhoughjr** [comment]
Thanks for the quick reply. Liking GRDB so far and it seems I can reason about ti effectively.

It started to occur to me I could do that probably as you were wrtting it.
Im not sure if I have explained the issue though.
One is my apps problem, but the other is more important and points to an api improvement imo.

It appears that @Query( _, in:DatabaseContext) is close to just accepting a queue or pool to me.
Unless there are some internals idk about it seems its only in the decorator so it can be passed
to the implementor of Queryable, and if I can ignore it using a pool in the same call site, cant it just pass in: as either a pool or a queue in the decorator?
The comments in Queryable say it can be a databaseQueue or some other type a publisher can be made from.

This way it will still be explicit in the decorator as to what db is accessed.

I hope it's more clear now what Im talking about. I realize it will be more obvious to me as it's what ive been working on for a bit.

If not for the @Query decorator confusion for me, its been pretty easy to pick up despite seeming daunting with the huge readme.

**Comment by groue** [comment]
I'm glad you found your solution! I you have an idea to make the documentation more clear, please tell: this may help other users :-)
