### ISSUE TITLE
SwiftUI views using EnvironmentStateObject receive multiple init calls

### ISSUE THREAD

**Issue by disbelief** [groue/GRDBQuery#33]
*(Disclaimer: I'm fairly new to SwiftUI and GRDBQuery)*

I've noticed that my SwiftUI views that use `@EnvironmentStateObject` to inject their view models are having `init` called multiple times. I'm not sure if this is intended behaviour or not, but it places some restrictions on what can be done in the makeObject block if it gets called multiple times.

Here's an example:

```swift
struct MyView: View {
    @EnvironmentStateObject private var viewModel: MyViewModel
    
    init() {
        print("MyView.init")
        
        _viewModel = EnvironmentStateObject {
            MyViewModel(dependencies: $0.dependencies)
        }

    var body: some View {
        Button {
            viewModel.doStuff()
        } label: {
            Text(viewModel.status)
        }
    }
}
```

```swift
final class MyViewModel: ObservableObject {
    @Published var status: String = "Idle"

    private var stuffUseCase: StuffUseCase

    init(dependencies: MyDependencies) {
        print("MyViewModel.init")
        self.stuffUseCase = dependencies.getStuffUseCase()
    }

    func doStuff() {
        self.status = "Working"
        DispatchQueue.global().async {
            self.stuffUseCase.doStuff()
            self.status = "Done"
        }
    }
}
```

When my app starts, the logs show the following before any navigation or interaction:

```
MyView.init
MyViewModel.init
MyView.init
MyViewModel.init
```

Is this to be expected?

**Comment by groue** [comment]
You're welcome! This video is really eye-opening. Open a new issue if the trouble persists (a short reproducing sample code would help then). Happy GRDBQuery!
