### ISSUE TITLE
@Query property not being restored by SwiftUI when view is updated

### ISSUE THREAD

**Issue by baoshan** [groue/GRDBQuery#34]
Given a view with a `@Query` wrapped property:

```
struct PlayerView: View {
    @Query<PlayerRequest>
    private var player: Player?

    init(id: Int) {
        self._ player = Query(PlayerRequest(id: id))
    }
}
```

Let’s put it into our app:
```
struct ContentView: View {
    @State private var id: Int = 0
    var body: some View {
        PlayerView(id: id)
        Button("Change Player") {
            self.id += 1
        }
    }
}
```

When `id` gets updated, just like `@State`, SwiftUI restores the previously cached `@Query` and overwrites the value we set in the initializer [(basically described here)](https://developer.apple.com/forums/thread/678871?answerId=671943022#671943022).

This means the `PlayerView` never gets updated. I can introduce an explicit identity to force the update:

```
PlayerView(id: id)
.id(id)
```

Is there a better approach? Thanks.

**Comment by groue** [comment]
Hello @baoshan,

Yes, `@Query` behaves like `@State` by default, as you can see. Adding an explicit `id` indeed forces SwiftUI to start afresh 👍

What you are looking for is another `Query` initializer:

```swift
struct PlayerView: View {
    @Query<PlayerRequest>
    private var player: Player?

    init(id: Int) {
        self._ player = Query(constant: PlayerRequest(id: id))
        //                    ~~~~~~~~
    }
}
```

The `constant` parameter name instructs `@Query` to disable any mutation of the request *from within* `PlayerView`. You can't put the "Change Player" button inside `PlayerView`, and mutate `$player.id += 1`. But the parent view now has full control on the request, and you no longer need to assign a specific id to your view.

For more information, see [Adding Parameters to Queryable Types](https://swiftpackageindex.com/groue/grdbquery/documentation/grdbquery/queryableparameters).

**Comment by baoshan** [comment]
Glad to know this is sooooo well-considered. 

Will spend more time with the great documentation.

Thanks, @groue!

**Comment by groue** [comment]
You're welcome! Happy GRDBQuery, and happy 2023!
