### ISSUE TITLE
Database queried twice with @Query

### ISSUE THREAD

**Issue by baoshan** [groue/GRDBQuery#35]
Given a request:

```
struct PlayerRequest: Queryable {
    static var defaultValue: Player? { nil }
    var id: Int
    func publisher(in reader: DatabaseReader)
    -> AnyPublisher<Player?, Error> {
        ValueObservation
            .tracking(Player.fetchOne(id: id))
            .publisher(in: reader)
            .eraseToAnyPublisher()
    }
}
```

Let’s have a root view:

```
struct PlayerRoot: View {
    @Query(PlayerRequest(id: 0))
    private var player: Player?
    var body: some View {
        Text("Foo")
    }
}
```

The `Player.fetchOne` static function is invoked twice.

How can I avoid the 2nd unnecessary query?

Thanks!

**Comment by groue** [comment]
Hello @baoshan,

I can't reproduce with the [demo app](https://github.com/groue/GRDBQuery/tree/main/Documentation/QueryDemo).

When I modify the `PlayerRequest` of the demo app by adding `print`:

```swift
struct PlayerRequest: Queryable {
    static var defaultValue: Player? { nil }
    
    func publisher(in dbQueue: DatabaseQueue) -> DatabasePublishers.Value<Player?> {
        ValueObservation
            .tracking(Player.fetchOne)
            .print("XXX") // <-
            .publisher(in: dbQueue)
    }
}
```

The app logs the expected output (with a single fetch):

```
XXX: start
XXX: fetch
XXX: tracked region: player(id,name,photoID,score)
XXX: value: nil
```

Maybe you can provide a sample code that reproduces your issue?

**Comment by baoshan** [comment]
I am still trying to isolate my issue.

At the current time, I find if replacing `DatabasePool(path:)` with `DatabaseQueue(path:)`, the double-query issue disappears.

Do you have any hints?

Thanks!

**Comment by baoshan** [comment]
The reason is that I’m using my fork (enabling FTS5) without updating to the latest commit.

Thanks very much for your help 🥇

**Comment by groue** [comment]
You were missing #1248 🙂
