### ISSUE TITLE
Package fails to build on Xcode 14.3 beta.

### ISSUE THREAD

**Issue by paulo-bc** [groue/GRDBQuery#36]
When opening the package in Xcode 14.3 beta (14E5197f), the build fails with error `'StateObject' is only available in [macOS 11.0 | iOS 14.0] or newer`.
Culprits are `EnvironmentStateObject.swift line 253` and `Query.swift line 172`.

This [StackOverflow thread](https://stackoverflow.com/questions/70414615/i-am-able-to-use-stateobject-in-ios-13-is-that-a-bug-or-is-it-real) seems to indicate that in runtime, accessing `StateObject` in iOS 13 would cause a exception to be raised, but I have not tested it myself.

[Apple documentation](https://developer.apple.com/documentation/swiftui/stateobject) says it is available in `iOS 14.0+, macOS 11.0+, tvOS 14.0+, watchOS 7.0+`, so maybe we could get a new version cut with those versions as minimum in the Package file?

Thanks!
🙇

**Comment by groue** [comment]
Hello @paulo-bc,

Thank you for the report!

**Comment by groue** [comment]
Version 0.6.0 has shipped 🚀
