### ISSUE TITLE
@Query use for searchable suggestedTokens

### ISSUE THREAD

**Issue by Polybear-Philippe** [groue/GRDBQuery#48]
I was trying to use @Query to feed the suggestedTokens parameter for a searchable list.   Here is an example of what I was trying to accomplish:

```
import SwiftUI
import GRDB
import GRDBQuery
import Combine

public struct Tag : Hashable, Codable, Identifiable, Equatable {
    private(set) public var id: Int64?
    public var tag: String
}

extension Tag: TableRecord, FetchableRecord, MutablePersistableRecord {
    enum Columns {
        static let id = Column(CodingKeys.id)
        static let tag = Column(CodingKeys.tag)
    }
    
    public mutating func didInsert(_ inserted: InsertionSuccess) {
        id = inserted.rowID
    }
}

public struct TagQuery: Queryable {

    public static var defaultValue: [Tag] { [] }

    public func publisher(in repository: Repository) -> AnyPublisher<[Tag], Error>  {

        ValueObservation.tracking { db in
            return try Tag.fetchAll(db)
        }
        .publisher(in: repository.reader, scheduling: .immediate)
        .eraseToAnyPublisher()

    }
}

struct Test: View {
    var data : [String] = ["A", "B", "C"]

    @Binding var searchTerm : String

    @State private var tokens: [Tag] = []

    @Query(TagQuery())
    private var suggestedTokens: [Tag]
    
    var body: some View {
        List {
            ForEach(data, id: \.self) { data in
                Text(data)
            }
        }
        .searchable(text: $searchTerm, tokens: $tokens, suggestedTokens: $suggestedTokens) {token in
            Text(token.tag)
        }
    }
}

```

it fails to compile with this error:

`
Cannot convert value of type 'Query<TagQuery>.Wrapper' to expected argument type 'Binding<[Token]>'
`

Is there a way to use @Query to feed the suggestedTokens list?

**Comment by groue** [comment]
Hello @Polybear-Philippe,

The [`searchable(text:tokens:suggestedTokens:placement:prompt:token:)`](https://developer.apple.com/documentation/swiftui/view/searchable(text:tokens:suggestedtokens:placement:prompt:token:)-9q3oc) api you are using accepts a `suggestedTokens` parameter that is a binding to a collection of suggested tokens.

SwiftUI bindings support two operations: *getting* and *setting* a value.

The `@Query` property wrapper does not support *setting* the observed value.

This explains the mismatch.

<sub>If you think about it, what should happen when you *set* the value of a `@Query` property? Write into the database? But nothing in the definition of `TagQuery ` allows such thing. That can't be.</sub>

You thus need a *writable storage* for the suggested items, such as a `@State` property. You may try something like:

```swift
struct Test: View {
    var data : [String] = ["A", "B", "C"]
    @Binding var searchTerm : String
    @State private var tokens: [Tag] = []
    // A storage for suggested tokens from which we can build a binding
    @State private var suggestedTokens2: [Tag] = []
    @Query(TagQuery())
    private var suggestedTokens: [Tag]
    
    var body: some View {
        List {
            ForEach(data, id: \.self) { data in
                Text(data)
            }
        }
        .searchable(text: $searchTerm, tokens: $tokens, suggestedTokens: $suggestedTokens2) { token in
            Text(token.tag)
        }
        // Update the suggested tokens when the database changes
        .onChange(of: suggestedTokens) { suggestedTokens2 = $0 }
    }
}
```

(This sample code was not tested. It's just an illustration of the technique which consists in dedicating a specific storage to the creation of a binding.)

**Comment by Polybear-Philippe** [comment]
Thanks!

I agree with the assertion that a search view would never need to update the database and understand your solution.   

Would using Binding.constant() also be another potential solution that would have the same implications?

**Comment by groue** [comment]
Yes, `Binding.constant` is a possibility. I don't know if this can create an issue in the search user interface or not. You can try!

**Comment by Polybear-Philippe** [comment]
It does work but it could only be because $suggestedTokens doesn't update while searching

**Comment by groue** [comment]
Thank you @Polybear-Philippe :-) Happy GRDB and GRDBQuery ;-)
