### ISSUE TITLE
Possibility to use this without the environment

### ISSUE THREAD

**Issue by Jasperav** [groue/GRDBQuery#6]
I really like the idea of this propertyWrapper! I was wondering though if it would be possible to use the wrapper without having an environment, but reusing a `DatabaseQueue` directly from a parameter? 

My views already hold an object in which the database context lives, so I was wondering if I can initialize a property annotated with `@Query` in the `init` block. This saves me some lines and it won't create a default in memory database.

Like this (just some pseudo code):

```
@Query
var players: [Player]

private let objectWithDatabase: MyObject

init(objectWithDatabase: MyObject) { 
    self.objectWithDatabase = objectWithDatabase
    self.players = .init(database: objectWithDatabase.db, ...)
}
```

Thanks!

**Comment by groue** [comment]
Hello @Jasperav,

I'm not sure it is _possible_ to define a type that accesses the environment, or not, depending on which initializer was called. Actually I'm 99% convinced it is not. But I'd be glad to be proven otherwise: please perform your experiments, and report your progress!

**Comment by groue** [comment]
Also, considering `@Query` was inspired by [`@FetchRequest`](https://developer.apple.com/documentation/swiftui/fetchrequest), and `@FetchRequest` can only access the database through the environment, I think we should really think twice, thrice, and even more, before removing this constraint.

We have all learned, or are about to learn, that SwiftUI is a **very cruel master**. When you don't play by the rule, you wind up flat on your bottom on the floor, clueless, contemplating the amount of refactoring you have to perform.

As a maintainer of this repository, I'm reluctant to support, in the long run, the consequences of _your_ convenience ;-)

**Comment by groue** [comment]
Interesting! I love to be refuted ;-) Thanks for taking the time to look at it.

**Comment by groue** [comment]
Moving to #7
