### ISSUE TITLE
Constructing a `Query` with `DatabaseContext` directly?

### ISSUE THREAD

**Issue by sashaweiss** [groue/GRDBQuery#61]
Hi @groue!

First off, love using GRDB (I use it extensively for work), and thank you for maintaining it. I've just started experimenting with GRDB and GRDBQuery in a personal project, and was wondering – would GRDBQuery ever support constructing a `Query` with a database context passed in `init`, rather than required to be part of the `Environment`?

Specifically, I'm thinking about the fact that `Query/database` is wrapped by an `@Environment`, and set during `init` via `self._database = Environment(keyPath)`. Is that necessary for some observable reason, or could `Query` also expose an `init` that takes a `DatabaseContext` directly?

It's not a huge deal – just thinking about dependency injection patterns that pass values directly, rather than pulling them from `Environment`. Thanks in advance!

**Comment by groue** [comment]
Hello @sashaweiss, 

Thanks for the compliments ;)

There isn't any reason for preventing `Query` from accepting a context directly. There is no such thing, currently, because I was focused on getting the context from the SwiftUI environment, as Apple does with similar APIs (`@FetchRequest`, `@Query`). I agree there are other techniques for achieving dependency injection 👍

Let's keep in mind that we need to avoid turning GRDBQuery into an unnecessary layer between the app and GRDB. Providing a ready-made support for the SwiftUI environment is a useful feature. If we make it possible to avoid the environment, what's left?

Maybe we need to answer this question before discussing a target api (or we can do both at the same time).

**Comment by sashaweiss** [comment]
> If we make it possible to avoid the environment, what's left?

Yeah, great question. In short, I'm getting a lot of value out of the fact that `Query` is a `DynamicProperty` and handles listening for updates from the database – it's a convenient abstraction over all the observation and update publishing. The fact that it hooks into `Environment` makes sense to me as a default (especially given the SwiftData abstractions you mentioned!), but it's not the primary value-add for me.

I'll also admit that I'm new to SwiftUI, and it's possible I'm mis-calibrated!

**Comment by sashaweiss** [comment]
Not least because I'm new to SwiftUI, I'm not sure what a target API would look like. Naively I thought to remove the `@Environment` from `private var database: Request.Context`, but that makes the `Environment`-based variant of the API strange.

For example, one could do `self.database = Environment(keyPath).wrappedValue` to extract the database context from the environment as it is during `init`...but would that be confusing or an anti-pattern somehow?

**Comment by groue** [comment]
> For example, one could do self.database = Environment(keyPath).wrappedValue to extract the database context from the environment as it is during init...but would that be confusing or an anti-pattern somehow?

:) This deserves a longer answer. Please hold on: there are a few SwiftUI facts to unwrap :)

**Comment by groue** [comment]
> the fact that `Query` is a `DynamicProperty`

This is what allows Query to access the environment _at the right moment_, i.e. when the view has been installed in the SwiftUI runtime.

The SwiftUI environment is not available in View initializers, or in the initializers of the view properties (including Query). It's too early. When a view is created, it does not belong to any rendering hierarchy yet, and there's no useful environment to read from.

But if you don't want to use the environment, this should not be a problem:

```
struct PlayerListView {
  @Query<PlayersRequest> var players

  // The caller is responsible for
  // providing a context, in a way
  // or another (exercise left to
  // the user of PlayerListView)
  init(
    databaseContext: DatabaseContext
  ) {
    _players = Query(PlayersRequest(), databaseContext: databaseContext)
  }

  var body: some View { ... }
}
```

Is this what you were thinking about? Do you have a clear idea of the technique you would use to provide the database context?

**Comment by sashaweiss** [comment]
Oh, the environment-readiness is a very salient detail! So if I understand correctly, using `@Environment` means that accessing `self.database` actually does a lookup in the `Environment`, which will fail (either falling back to a default value or fatally?) – so in practice `self.database` access (i.e., to set up `self.tracker`) doesn't occur until after environment is set up?

---

> Is this what you were thinking about? Do you have a clear idea of the technique you would use to provide the database context?

What you outlined (passing a `DatabaseContext`, or rather a `Value.Context`, to `Query/init`) is exactly what I was picturing. I'm setting up my `DatabaseContext` during app launch, and so will have it available during view `init`.

If this were supported, though, IIUC `self.database` could no longer use the `@Environment` property wrapper. Would something like the following be reasonable to represent the dual nature of `self.database` (either available during `init`, or intended to be fetched dynamically from `Environment`)?
```swift
private enum DatabaseContextProvider {
    case value(DatabaseContext)
    case environment(Environment<DatabaseContext>)
}

private let databaseProvider: DatabaseContextProvider // set during init
private var database: DatabaseContext {
    switch databaseProvider {
    case .value(let database): return database
    case .environment(let database): return database.wrappedValue
    }
}
```

(There'll also be an explosion of `init`s, as each of the initial/constant/binding `Query/init` variants would now need a mode for taking the `DatabaseContext` directly. This point could be addressed by exposing `Query/Configuration` as an `init` argument?)

**Comment by groue** [comment]
> Oh, the environment-readiness is a very salient detail! So if I understand correctly, using `@Environment` means that accessing `self.database` actually does a lookup in the `Environment`, which will fail (either falling back to a default value or fatally?) – so in practice `self.database` access (i.e., to set up `self.tracker`) doesn't occur until after environment is set up?

Yes. More precisely, the environment should only be read from the `update` method of DynamicProperty. SwiftUI calls this method automatically before the view body is rendered, and after the environment is ready.

> What you outlined (passing a `DatabaseContext`, or rather a `Value.Context`, to `Query/init`) is exactly what I was picturing. I'm setting up my `DatabaseContext` during app launch, and so will have it available during view `init`.

OK. But why not putting this context in the environment, then?

**Comment by sashaweiss** [comment]
> OK. But why not putting this context in the environment, then?

Fair question! In short, stylistically I prefer the explicit nature of passing the context to an `init` rather than relying on one being present in the environment, as a dependency-injection pattern. In practice, I'm using this currently in a small and not-very-complex personal project. So, having the context in the environment is fine for me for now.

I sincerely appreciate all the explanations – I've learned a lot! If, in the future, I find myself reaching for GRDBQuery in a more complex or constrained project (e.g., at work) and have a need for this feature again, I'll follow up here :)

Thanks again @groue, for this discussion and for maintaining GRDBQuery!

**Comment by groue** [comment]
All right @sashaweiss 👍

As you can see, there is no hostility against your idea: we just need a compelling case, something that can not be achieved, or is somewhat impractical, with the current API.

Happy GRDB, and happy holidays!
